# Generated by Django 5.0.7 on 2024-08-29 14:49

import apps.categories.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriesModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "serial_number",
                    apps.categories.models.CustomIncrementalField(
                        blank=True, editable=False
                    ),
                ),
                ("nomenclature", models.CharField(max_length=10)),
                ("code", models.CharField(max_length=10)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=32768, null=True
                    ),
                ),
                (
                    "norme",
                    models.TextField(
                        blank=True, default="", max_length=32768, null=True
                    ),
                ),
                (
                    "fondement",
                    models.TextField(
                        blank=True, default="", max_length=16384, null=True
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True, default="", max_length=16384, null=True
                    ),
                ),
                (
                    "object",
                    models.TextField(
                        blank=True, default="", max_length=16384, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="categories_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="categories_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "nomenclature",
                            "code",
                            "code",
                            "object",
                            "condition",
                            "norme",
                            "fondement",
                        ],
                        name="categories_nomencl_28a79e_idx",
                    )
                ],
            },
        ),
    ]
