# Generated by Django 5.0.7 on 2024-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "categories",
            "0003_remove_categoriesmodel_categories_nomencl_28a79e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriesmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
