# Generated by Django 5.0.7 on 2024-10-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0010_remove_binaryclassificationmodelsmodel_category_and_more"),
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="model_annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="model_annotator",
                to="ai_models.ai_modelsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="model_annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_model_annotator",
                to="ai_models.ai_modelsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="extractionbinaryannotationsmodel",
            name="model_annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_binary_model_annotator",
                to="ai_models.ai_modelsmodel",
            ),
        ),
    ]
