# Generated by Django 5.0.7 on 2024-08-29 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_models", "0001_initial"),
        ("datasets", "0001_initial"),
        ("decisions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryAnnotationsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_annotations_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_annotations_decision",
                        to="decisions.datasetsdecisionsmodel",
                    ),
                ),
                (
                    "human_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_annotations_human_annotator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_annotations_label",
                        to="datasets.labels",
                    ),
                ),
                (
                    "model_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="model_annotator",
                        to="ai_models.binaryclassificationmodelsmodel",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_annotations_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "binary_annotations",
            },
        ),
        migrations.CreateModel(
            name="ExtractionAnnotationsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_annotations_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_model_annotator",
                        to="ai_models.extractionmodelsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_annotations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtractionBinaryAnnotationsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "binary_annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_extraction",
                        to="annotations.binaryannotationsmodel",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_binary",
                        to="annotations.extractionannotationsmodel",
                    ),
                ),
                (
                    "human_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_human_annotator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_binary_model_annotator",
                        to="ai_models.extractionmodelsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_binary_annotations",
            },
        ),
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="binary_annotations",
            field=models.ManyToManyField(
                blank=True,
                related_name="extraction_annotations",
                through="annotations.ExtractionBinaryAnnotationsModel",
                to="annotations.binaryannotationsmodel",
            ),
        ),
        migrations.CreateModel(
            name="TextAnnotationsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", max_length=32768, null=True
                    ),
                ),
                (
                    "start_offset",
                    models.IntegerField(blank=True, default=-1, null=True),
                ),
                ("end_offset", models.IntegerField(blank=True, default=-1, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_annotations_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_annotations_decision",
                        to="decisions.datasetsdecisionsmodel",
                    ),
                ),
                (
                    "human_annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_annotations_human_annotator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_annotations_label",
                        to="datasets.labels",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_annotations_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "text_annotations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtractionTextAnnotationsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_text",
                        to="annotations.extractionannotationsmodel",
                    ),
                ),
                (
                    "text_annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="text_extraction",
                        to="annotations.textannotationsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_text_annotations",
            },
        ),
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="text_annotations",
            field=models.ManyToManyField(
                blank=True,
                related_name="extraction_annotations",
                through="annotations.ExtractionTextAnnotationsModel",
                to="annotations.textannotationsmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="binaryannotationsmodel",
            index=models.Index(fields=["label"], name="binary_anno_label_i_23638e_idx"),
        ),
        migrations.AddIndex(
            model_name="binaryannotationsmodel",
            index=models.Index(
                fields=["decision"], name="binary_anno_decisio_22823c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionbinaryannotationsmodel",
            index=models.Index(
                fields=["extraction"], name="extraction__extract_9c7cf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionbinaryannotationsmodel",
            index=models.Index(
                fields=["binary_annotation"], name="extraction__binary__afbbc4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionbinaryannotationsmodel",
            constraint=models.UniqueConstraint(
                fields=("extraction", "binary_annotation"),
                name="unique_extraction_binary_annotation",
            ),
        ),
        migrations.AddIndex(
            model_name="extractiontextannotationsmodel",
            index=models.Index(
                fields=["extraction"], name="extraction__extract_44f142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractiontextannotationsmodel",
            index=models.Index(
                fields=["text_annotation"], name="extraction__text_an_86e3a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractiontextannotationsmodel",
            constraint=models.UniqueConstraint(
                fields=("extraction", "text_annotation"),
                name="unique_extraction_text_annotation",
            ),
        ),
    ]
