# Generated by Django 5.0.7 on 2025-02-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0002_alter_binaryannotationsmodel_model_annotator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="binaryannotationsmodel",
            options={"ordering": ["-created_at"]},
        ),
    ]
