# Generated by Django 5.0.7 on 2025-02-07 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0003_alter_binaryannotationsmodel_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="human_annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_annotator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
