# Generated by Django 5.0.7 on 2025-02-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0004_alter_binaryannotationsmodel_human_annotator"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryannotationsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textannotationsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
