# Generated by Django 5.0.7 on 2025-02-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0005_binaryannotationsmodel_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="binaryannotationsmodel",
            name="human_annotator",
        ),
        migrations.RemoveField(
            model_name="textannotationsmodel",
            name="human_annotator",
        ),
    ]
