# Generated by Django 5.0.7 on 2025-04-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0020_remove_ai_modelsmodel_model_path"),
        ("annotations", "0006_remove_binaryannotationsmodel_human_annotator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryannotationsmodel",
            name="trained_model_annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="trained_model_annotator",
                to="ai_models.aimodeltrainingsmodel",
            ),
        ),
    ]
