# Generated by Django 5.0.7 on 2025-04-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0008_alter_binaryannotationsmodel_creator_and_more"),
        ("datasets", "0006_remove_labels_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="binary_annotations_label",
                to="datasets.labels",
            ),
        ),
    ]
