# Generated by Django 5.0.7 on 2025-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0009_alter_binaryannotationsmodel_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("unannotated", "Non annoté"),
                    ("pending", "En attente"),
                    ("validated", "Validée"),
                    ("rejected", "Rejetée"),
                ],
                default="unannotated",
                max_length=12,
            ),
        ),
    ]
