# Generated by Django 5.0.7 on 2025-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0010_alter_binaryannotationsmodel_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
