# Generated by Django 5.0.7 on 2025-04-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0011_alter_binaryannotationsmodel_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractionannotationsmodel",
            name="binary_annotations",
        ),
        migrations.RemoveField(
            model_name="extractionannotationsmodel",
            name="state",
        ),
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="json_object",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="model_annotator",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
