# Generated by Django 5.0.7 on 2025-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0012_remove_extractionannotationsmodel_binary_annotations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
