# Generated by Django 5.0.7 on 2025-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0013_extractionannotationsmodel_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractionbinaryannotationsmodel",
            name="binary_annotation",
        ),
        migrations.RemoveField(
            model_name="extractionbinaryannotationsmodel",
            name="extraction",
        ),
        migrations.RemoveField(
            model_name="extractionbinaryannotationsmodel",
            name="human_annotator",
        ),
        migrations.RemoveField(
            model_name="extractionbinaryannotationsmodel",
            name="model_annotator",
        ),
        migrations.RemoveConstraint(
            model_name="extractiontextannotationsmodel",
            name="unique_extraction_text_annotation",
        ),
        migrations.RemoveIndex(
            model_name="extractiontextannotationsmodel",
            name="extraction__text_an_86e3a8_idx",
        ),
        migrations.RenameField(
            model_name="extractionannotationsmodel",
            old_name="json_object",
            new_name="llm_json_result",
        ),
        migrations.RemoveField(
            model_name="extractionannotationsmodel",
            name="text_annotations",
        ),
        migrations.RemoveField(
            model_name="extractiontextannotationsmodel",
            name="text_annotation",
        ),
        migrations.AddField(
            model_name="extractiontextannotationsmodel",
            name="end_offset",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name="extractiontextannotationsmodel",
            name="label",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="extractiontextannotationsmodel",
            name="start_offset",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name="extractiontextannotationsmodel",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("annotated", "Annotée"),
                    ("validated", "Validée"),
                    ("corrected", "Corrigée"),
                ],
                default="annotated",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractiontextannotationsmodel",
            name="text",
            field=models.TextField(blank=True, default="", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="state",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddIndex(
            model_name="extractiontextannotationsmodel",
            index=models.Index(fields=["state"], name="extraction__state_795518_idx"),
        ),
        migrations.AddConstraint(
            model_name="extractiontextannotationsmodel",
            constraint=models.UniqueConstraint(
                fields=("extraction",), name="unique_extraction_text_annotation"
            ),
        ),
        migrations.DeleteModel(
            name="ExtractionBinaryAnnotationsModel",
        ),
    ]
