# Generated by Django 5.0.7 on 2025-05-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0014_remove_extractionbinaryannotationsmodel_binary_annotation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="extractiontextannotationsmodel",
            name="extraction__state_795518_idx",
        ),
        migrations.RemoveField(
            model_name="extractiontextannotationsmodel",
            name="state",
        ),
    ]
