# Generated by Django 5.0.7 on 2025-05-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0015_remove_extractiontextannotationsmodel_extraction__state_795518_idx_and_more",
        ),
        ("decisions", "0013_alter_datasetsdecisionsmodel_dataset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ext_annotations_decision",
                to="decisions.datasetsdecisionsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_annotations_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
