# Generated by Django 5.0.7 on 2025-05-01 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0016_extractionannotationsmodel_decision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_annotations_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
