# Generated by Django 5.0.7 on 2025-05-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0017_alter_extractionannotationsmodel_creator"),
        ("decisions", "0013_alter_datasetsdecisionsmodel_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionannotationsmodel",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ext_annotations_decision",
                to="decisions.datasetsdecisionsmodel",
            ),
        ),
    ]
