# Generated by Django 5.0.7 on 2025-05-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0018_alter_extractionannotationsmodel_decision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="extractiontextannotationsmodel",
            name="unique_extraction_text_annotation",
        ),
    ]
