# Generated by Django 5.0.7 on 2025-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0019_remove_extractiontextannotationsmodel_unique_extraction_text_annotation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="state",
            field=models.CharField(
                blank=True, default="unannotated", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="textannotationsmodel",
            name="state",
            field=models.CharField(
                blank=True, default="unannotated", max_length=255, null=True
            ),
        ),
    ]
