# Generated by Django 5.0.7 on 2025-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0020_alter_binaryannotationsmodel_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryannotationsmodel",
            name="state",
            field=models.CharField(
                blank=True, default="annotated", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="textannotationsmodel",
            name="state",
            field=models.CharField(
                blank=True, default="annotated", max_length=255, null=True
            ),
        ),
    ]
