# Generated by Django 5.0.7 on 2025-05-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0022_extractionannotationsmodel_updater"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractionannotationsmodel",
            name="updater",
        ),
    ]
