# Generated by Django 5.0.7 on 2025-05-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0023_remove_extractionannotationsmodel_updater"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_annotations_updater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
