# Generated by Django 5.0.7 on 2025-05-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0024_extractionannotationsmodel_updater"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionannotationsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
