# Generated by Django 5.0.7 on 2024-08-29 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDecisionsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("chambre", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "juridiction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("formation", models.TextField(blank=True, max_length=2048, null=True)),
                (
                    "texte",
                    models.TextField(
                        blank=True, default="", max_length=100000, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="decisions_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "raw_decisions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetsDecisionsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dataset_decision",
                        to="datasets.datasetsmodel",
                    ),
                ),
                (
                    "raw_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="raw_decision",
                        to="decisions.rawdecisionsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "datasets_decisions",
            },
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["rg"], name="raw_decisio_rg_17fc2d_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["date"], name="raw_decisio_date_dbe88a_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["ville"], name="raw_decisio_ville_f698d1_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(
                fields=["juridiction"], name="raw_decisio_juridic_1ac338_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetsdecisionsmodel",
            constraint=models.UniqueConstraint(
                fields=("dataset", "raw_decision"), name="unique_dataset_raw_decision"
            ),
        ),
    ]
