# Generated by Django 5.0.7 on 2024-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0004_alter_datasetsmodel_deleted"),
        ("decisions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetsdecisionsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="datasetsdecisionsmodel",
            index=models.Index(
                fields=["dataset"], name="datasets_de_dataset_64490a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetsdecisionsmodel",
            index=models.Index(
                fields=["raw_decision"], name="datasets_de_raw_dec_9f4b51_idx"
            ),
        ),
    ]
