# Generated by Django 5.0.7 on 2024-10-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0003_rawdecisionsmodel_j_rg"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rawdecisionsmodel",
            name="raw_decisio_rg_17fc2d_idx",
        ),
        migrations.RemoveField(
            model_name="rawdecisionsmodel",
            name="rg",
        ),
    ]
