# Generated by Django 5.0.7 on 2024-10-28 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "decisions",
            "0004_remove_rawdecisionsmodel_raw_decisio_rg_17fc2d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["j_rg"], name="raw_decisio_j_rg_945ee8_idx"),
        ),
    ]
