# Generated by Django 5.0.7 on 2024-10-29 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0005_rawdecisionsmodel_raw_decisio_j_rg_945ee8_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rawdecisionsmodel",
            name="raw_decisio_date_dbe88a_idx",
        ),
        migrations.RemoveIndex(
            model_name="rawdecisionsmodel",
            name="raw_decisio_ville_f698d1_idx",
        ),
        migrations.RemoveIndex(
            model_name="rawdecisionsmodel",
            name="raw_decisio_juridic_1ac338_idx",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="juridiction",
            new_name="j_chambre",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="date",
            new_name="j_date",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="formation",
            new_name="j_formation",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="chambre",
            new_name="j_juridiction",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="ville",
            new_name="j_ville",
        ),
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="texte",
            new_name="texte_net",
        ),
        migrations.AddField(
            model_name="rawdecisionsmodel",
            name="j_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="rawdecisionsmodel",
            name="j_nac",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="rawdecisionsmodel",
            name="j_zone_net",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["j_date"], name="raw_decisio_j_date_03979b_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(
                fields=["j_ville"], name="raw_decisio_j_ville_3bb6ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(
                fields=["j_juridiction"], name="raw_decisio_j_jurid_16bd1d_idx"
            ),
        ),
    ]
