# Generated by Django 5.0.7 on 2024-10-29 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "decisions",
            "0006_remove_rawdecisionsmodel_raw_decisio_date_dbe88a_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdecisionsmodel",
            name="j_formation",
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["j_id"], name="raw_decisio_j_id_b791e9_idx"),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["j_nac"], name="raw_decisio_j_nac_691e40_idx"),
        ),
    ]
