# Generated by Django 5.0.7 on 2024-10-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0007_remove_rawdecisionsmodel_j_formation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdecisionsmodel",
            name="creator",
        ),
    ]
