# Generated by Django 5.0.7 on 2024-11-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0008_remove_rawdecisionsmodel_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawdecisionsmodel",
            old_name="j_zone_net",
            new_name="j_zones_net",
        ),
    ]
