# Generated by Django 5.0.7 on 2024-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0009_rename_j_zone_net_rawdecisionsmodel_j_zones_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdecisionsmodel",
            name="j_id",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
