# Generated by Django 5.0.7 on 2024-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0010_alter_rawdecisionsmodel_j_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdecisionsmodel",
            name="j_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name="rawdecisionsmodel",
            index=models.Index(fields=["j_type"], name="raw_decisio_j_type_2b6574_idx"),
        ),
    ]
