# Generated by Django 5.0.7 on 2025-01-14 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0011_rawdecisionsmodel_j_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasetsdecisionsmodel",
            options={"ordering": ["add_date"]},
        ),
        migrations.AddField(
            model_name="datasetsdecisionsmodel",
            name="add_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
