# Generated by Django 5.0.7 on 2025-05-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0013_alter_datasetsdecisionsmodel_dataset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasetsdecisionsmodel",
            options={"ordering": ["-raw_decision__j_date", "-raw_decision__j_ville"]},
        ),
        migrations.AlterModelOptions(
            name="rawdecisionsmodel",
            options={"ordering": ["-j_date", "-j_ville"]},
        ),
    ]
