# Generated by Django 5.0.7 on 2024-09-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_categoriesmodel_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriesmodel",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
