# Generated by Django 5.0.7 on 2024-08-29 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryClassificationModelsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=4096, null=True
                    ),
                ),
                ("model_path", models.FileField(upload_to="models/")),
                ("model_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="binary_classification_models_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "binary_classification_models",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="binary_clas_name_12522f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractionModelsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=4096, null=True
                    ),
                ),
                ("model_path", models.FileField(upload_to="models/")),
                ("model_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="extraction_models_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extraction_models",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="extraction__name_f4f485_idx")
                ],
            },
        ),
    ]
