# Generated by Django 5.0.7 on 2024-08-29 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0003_binarytrainingsmodel"),
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="binarytrainingsmodel",
            options={"ordering": ["model"]},
        ),
        migrations.RemoveIndex(
            model_name="binarytrainingsmodel",
            name="trainings_model_i_ba89e1_idx",
        ),
        migrations.RemoveField(
            model_name="binarytrainingsmodel",
            name="prompt",
        ),
        migrations.AddIndex(
            model_name="binarytrainingsmodel",
            index=models.Index(fields=["model"], name="binary_trai_model_i_c654fe_idx"),
        ),
        migrations.AlterModelTable(
            name="binarytrainingsmodel",
            table="binary_trainings",
        ),
    ]
