# Generated by Django 5.0.7 on 2024-10-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0004_alter_binarytrainingsmodel_options_and_more"),
        ("categories", "0005_alter_categoriesmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryclassificationmodelsmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="binary_classification_models_category",
                to="categories.categoriesmodel",
            ),
        ),
        migrations.AddField(
            model_name="extractionmodelsmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="extraction_models_category",
                to="categories.categoriesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="binaryclassificationmodelsmodel",
            name="model_path",
            field=models.FileField(
                upload_to="models/<django.db.models.fields.UUIDField>/<django.db.models.fields.CharField>/<django.db.models.fields.DateTimeField>/"
            ),
        ),
        migrations.AlterField(
            model_name="extractionmodelsmodel",
            name="model_path",
            field=models.FileField(
                upload_to="models/<django.db.models.fields.UUIDField>/<django.db.models.fields.CharField>/<django.db.models.fields.DateTimeField>/"
            ),
        ),
    ]
