# Generated by Django 5.0.7 on 2024-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0005_binaryclassificationmodelsmodel_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryclassificationmodelsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="extractionmodelsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
