# Generated by Django 5.0.7 on 2024-10-14 12:44

import ai_models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0006_binaryclassificationmodelsmodel_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryclassificationmodelsmodel",
            name="serial_number",
            field=ai_models.models.CustomIncrementalField(
                blank=True, default=1, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionmodelsmodel",
            name="serial_number",
            field=ai_models.models.CustomIncrementalField(
                blank=True, default=1, editable=False, null=True
            ),
        ),
    ]
