# Generated by Django 5.0.7 on 2024-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0010_remove_binaryclassificationmodelsmodel_category_and_more"),
        ("annotations", "0002_alter_binaryannotationsmodel_model_annotator_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BinaryClassificationModelsModel",
        ),
        migrations.DeleteModel(
            name="BinaryTrainingsModel",
        ),
        migrations.DeleteModel(
            name="ExtractionModelsModel",
        ),
        migrations.AddIndex(
            model_name="ai_modelsmodel",
            index=models.Index(fields=["name"], name="ai_models_name_475fb9_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodeltrainingsmodel",
            index=models.Index(fields=["model"], name="model_train_model_i_0c4f51_idx"),
        ),
    ]
