# Generated by Django 5.0.7 on 2024-10-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0013_promptsmodel_serial_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promptsmodel",
            options={"ordering": ["serial_number"]},
        ),
    ]
