# Generated by Django 5.0.7 on 2025-02-27 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0014_alter_promptsmodel_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodeltrainingsmodel",
            name="training_parameters",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="AiModelTypesModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="model_types_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model_types",
                "ordering": ["type"],
            },
        ),
        migrations.AddField(
            model_name="aimodeltrainingsmodel",
            name="type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="training_type",
                to="ai_models.aimodeltypesmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="aimodeltypesmodel",
            index=models.Index(fields=["type"], name="model_types_type_40b782_idx"),
        ),
    ]
