# Generated by Django 5.0.7 on 2025-04-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0018_rename_dataset_aimodeltrainingsmodel_datasets"),
        ("datasets", "0006_remove_labels_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai_modelsmodel",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ai_models_type",
                to="ai_models.aimodeltypesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="aimodeltrainingsmodel",
            name="datasets",
            field=models.ManyToManyField(
                blank=True, related_name="training_dataset", to="datasets.datasetsmodel"
            ),
        ),
    ]
