# Generated by Django 5.0.7 on 2025-04-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0019_ai_modelsmodel_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai_modelsmodel",
            name="model_path",
        ),
    ]
