# Generated by Django 5.0.7 on 2024-08-29 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0002_promptsmodel"),
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryTrainingsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "training_status",
                    models.CharField(default="pending", max_length=255),
                ),
                (
                    "training_result",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "training_log",
                    models.TextField(
                        blank=True, default="", max_length=32768, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trainings_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="training_dataset",
                        to="datasets.datasetsmodel",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="training_model",
                        to="ai_models.binaryclassificationmodelsmodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="training_prompt",
                        to="ai_models.promptsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "trainings",
                "ordering": ["model", "prompt"],
                "indexes": [
                    models.Index(
                        fields=["model", "prompt"], name="trainings_model_i_ba89e1_idx"
                    )
                ],
            },
        ),
    ]
