# Generated by Django 5.0.7 on 2024-10-14 12:57

import apps.ai_models.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0007_binaryclassificationmodelsmodel_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryclassificationmodelsmodel",
            name="serial_number",
            field=apps.ai_models.models.CustomIncrementalField(
                blank=True, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="extractionmodelsmodel",
            name="serial_number",
            field=apps.ai_models.models.CustomIncrementalField(
                blank=True, editable=False
            ),
        ),
    ]
