# Generated by Django 5.0.7 on 2024-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_models",
            "0008_alter_binaryclassificationmodelsmodel_serial_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryclassificationmodelsmodel",
            name="model_type",
            field=models.CharField(
                blank=True,
                default="binary_classification_model",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractionmodelsmodel",
            name="model_type",
            field=models.CharField(
                blank=True, default="extraction_model", max_length=255, null=True
            ),
        ),
    ]
