# Generated by Django 5.0.7 on 2024-10-17 14:29

import apps.ai_models.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0009_alter_binaryclassificationmodelsmodel_model_type_and_more"),
        ("categories", "0005_alter_categoriesmodel_options"),
        ("datasets", "0006_remove_labels_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="binaryclassificationmodelsmodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="binaryclassificationmodelsmodel",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="binarytrainingsmodel",
            name="model",
        ),
        migrations.RemoveField(
            model_name="binarytrainingsmodel",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="binarytrainingsmodel",
            name="dataset",
        ),
        migrations.RemoveField(
            model_name="extractionmodelsmodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="extractionmodelsmodel",
            name="creator",
        ),
        migrations.CreateModel(
            name="Ai_ModelsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "serial_number",
                    apps.ai_models.models.CustomIncrementalField(
                        blank=True, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=4096, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_path",
                    models.FileField(
                        upload_to="models/<django.db.models.fields.UUIDField>/<django.db.models.fields.CharField>/<django.db.models.fields.DateTimeField>/"
                    ),
                ),
                ("model_type", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ai_models_category",
                        to="categories.categoriesmodel",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ai_models_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiModelTrainingsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "training_status",
                    models.CharField(default="pending", max_length=255),
                ),
                (
                    "training_result",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "training_log",
                    models.TextField(
                        blank=True, default="", max_length=32768, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trainings_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="training_dataset",
                        to="datasets.datasetsmodel",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="training_model",
                        to="ai_models.ai_modelsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "model_trainings",
                "ordering": ["model"],
            },
        ),
    ]
