# Generated by Django 5.0.7 on 2024-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0011_delete_binaryclassificationmodelsmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
